### ISSUE TITLE
[Chrome]: Ошибка при отправлении сообщения.

### ISSUE THREAD

**Issue by StirItUp** [SthephanShinkufag/Dollchan-Extension-Tools#1218]
Собственно вот описание, которое выскакивает в хроме:

Тред недоступен: №26204018): 
Внутренняя ошибка:
TypeError: Cannot read property 'forEach' of undefined
    at WorkerPool.clearWorkers (file:///C:/Users/TheOnly/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ipnoalfffblkaodfmipjjgkfbgcfadad/18.4.26.0_0/Dollchan_Extension_Tools.es6.user.js:2038:21)
    at TasksPool [as endFn] (file:///C:/Users/TheOnly/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ipnoalfffblkaodfmipjjgkfbgcfadad/18.4.26.0_0/Dollchan_Extension_Tools.es6.user.js:5937:19)
    at TasksPool.completeTasks (file:///C:/Users/TheOnly/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ipnoalfffblkaodfmipjjgkfbgcfadad/18.4.26.0_0/Dollchan_Extension_Tools.es6.user.js:1944:10)
    at Object.preloadImages (file:///C:/Users/TheOnly/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ipnoalfffblkaodfmipjjgkfbgcfadad/18.4.26.0_0/Dollchan_Extension_Tools.es6.user.js:5969:16)
    at Thread._addPost (file:///C:/Users/TheOnly/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ipnoalfffblkaodfmipjjgkfbgcfadad/18.4.26.0_0/Dollchan_Extension_Tools.es6.user.js:13231:17)
    at Thread._importPosts (file:///C:/Users/TheOnly/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ipnoalfffblkaodfmipjjgkfbgcfadad/18.4.26.0_0/Dollchan_Extension_Tools.es6.user.js:13266:17)
    at Thread._parsePosts (file:///C:/Users/TheOnly/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ipnoalfffblkaodfmipjjgkfbgcfadad/18.4.26.0_0/Dollchan_Extension_Tools.es6.user.js:13482:21)
    at Thread._loadNewFromBuilder (file:///C:/Users/TheOnly/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ipnoalfffblkaodfmipjjgkfbgcfadad/18.4.26.0_0/Dollchan_Extension_Tools.es6.user.js:13403:40)
    at ajaxPostsLoad.then.pBuilder (file:///C:/Users/TheOnly/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ipnoalfffblkaodfmipjjgkfbgcfadad/18.4.26.0_0/Dollchan_Extension_Tools.es6.user.js:13164:32)
    at args (file:///C:/Users/TheOnly/AppData/Local/Google/Chrome/User%20Data/Default/Extensions/ipnoalfffblkaodfmipjjgkfbgcfadad/18.4.26.0_0/Dollchan_Extension_Tools.es6.user.js:1862:18)

**Comment by SthephanShinkufag** [comment]
Ошибка всегда выскакивает, или только иногда?

**Comment by StirItUp** [comment]
После каждого сообщения. Отладка:
{
	"version": "18.4.26.0.f6f5fdf",
	"location": "https://2ch.hk/vg/res/26204018.html",
	"nav": {
		"ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36",
		"scriptHandler": "WebExtension",
		"isESNext": true,
		"isFirefox": false,
		"firefoxVer": 0,
		"isWebkit": true,
		"isChrome": true,
		"isSafari": false,
		"isPresto": false,
		"isMsEdge": false,
		"isGM": false,
		"isNewGM": false,
		"isChromeStorage": true,
		"isScriptStorage": false,
		"isGlobal": true,
		"hasGMXHR": false,
		"canPlayMP3": true,
		"hasTemplate": true,
		"hasWorker": false
	},
	"Cfg": {
		"timePattern": "dd+nn+yy+w+hh+ii+ss",
		"addVocaroo": 0,
		"updScript": 0,
		"expandPanel": 1,
		"spells": "[1522907179403,[[1,\"/обосранд|Кеочмо|калзандер|К'екопукс|кал жуете|калтандер|дерьмандерс|Кеопук|ТУНДРАПАРАША|КАЛАПУК|АБАСРАНДИР|obосраNдера |O B O S R A N D E R|shiттандер|калопук|каlopok|обосран|Обоcрандер/i\",null],[3,\"/z917323\\\\.jpg/\",[\"vg\",23509555]],[4,266858368,[\"vg\",23509555]],[6,\"Аноним ID: Иларион Боримирович\",[\"po\",27560934]],[6,\"Аноним ID: Феофилакт Мартимьянович\",[\"po\",25647957]],[255,[[522,\"\",null],[1,\"/шари(?:ер|[йяю]ч?|ы)/i\",null]]],[255,[[522,\"\",null],[255,[[5,\"/крым|HOBOPOC|[лд]нр/i\",null]]]]]],false,false]",
		"webmVolume": 86,
		"sortSpells": 1,
		"delHiddPost": 1,
		"cfgWinX": "left: 702px",
		"cfgWinY": "top: 180px",
		"cfgTab": "info",
		"textaWidth": 429,
		"textaHeight": 293,
		"preLoadImgs": 1,
		"findImgFile": 1,
		"replyWinDrag": 1,
		"replyWinY": "top: 139px",
		"replyWinX": "left: 1164px",
		"altCaptcha": 1,
		"updDollchan": 0
	},
	"sSpells": [
		"#exp(/обосранд|Кеочмо|калзандер|К'екопукс|кал жуете|калтандер|дерьмандерс|Кеопук|ТУНДРАПАРАША|КАЛАПУК|АБАСРАНДИР|obосраNдера |O B O S R A N D E R|shiттандер|калопук|каlopok|обосран|Обоcрандер/i) |",
		"#imgn[vg,23509555](/z917323\\.jpg/) |",
		"#ihash[vg,23509555](266858368) |",
		"#name[po,27560934](Аноним ID: Иларион Боримирович) |",
		"#name[po,25647957](Аноним ID: Феофилакт Мартимьянович) |",
		"(#op & #exp(/шари(?:ер|[йяю]ч?|ы)/i)) | (",
		"    #op &",
		"    (#subj(/крым|HOBOPOC|[лд]нр/i))",
		")"
	],
	"oSpells": "[1522907179403,[[1,\"/обосранд|Кеочмо|калзандер|К'екопукс|кал жуете|калтандер|дерьмандерс|Кеопук|ТУНДРАПАРАША|КАЛАПУК|АБАСРАНДИР|obосраNдера |O B O S R A N D E R|shiттандер|калопук|каlopok|обосран|Обоcрандер/i\"],[255,[[522,\"\"],[1,\"/шари(?:ер|[йяю]ч?|ы)/i\"]]],[255,[[522,\"\"],[5,\"/крым|HOBOPOC|[лд]нр/i\"]]]],null,null]",
	"perf": {
		"Imageboard check": 2,
		"Storage loading": 91,
		"Init": 12,
		"Read my posts": 47,
		"Replace delform": 2,
		"Parse delform": 102,
		"Parse postform": 28,
		"Init keybinds": 1,
		"Init page": 7,
		"Add panel": 6,
		"Init AJAX": 4,
		"Preload images": 11,
		"Audio links": 4,
		"Video links": 17,
		"Image names": 11,
		"Reflinks map": 25,
		"Apply CSS": 5,
		"Display page": 0,
		"Infinity scroll": 0,
		"Hide posts": 6,
		"Image-links": 1,
		"Scroll page": 0,
		"Всего": 382
	}
}

**Comment by StirItUp** [comment]
Последовал совету #1208 и сбросил настройки.
Все заработало! Проблем никаких нет.
Извиняюсь за беспокойство и спасибо за плагин!

**Comment by SthephanShinkufag** [comment]
Спасибо за предоставленную инфу, проблема оказалась в опциях `"Предварительно загружать картинки*"` и `"Распознавать файлы, встроенные в картинках*"`.
Буду чинить.

**Comment by SthephanShinkufag** [comment]
Ошибка исправлена, обновил версию, сейчас прилетит обновлённое хроморасширение.
