### ISSUE TITLE
Скрипт не работает в некоторых сохраненных тредах на Архиваче

### ISSUE THREAD

**Issue by xDShot** [SthephanShinkufag/Dollchan-Extension-Tools#798]
В этих тредах:

http://arhivach.org/thread/89806/
http://arhivach.org/thread/89063/

не работает куклоскрипт (нет значка в правом нижнем углу, посты не отображаются при наведении на ответ, и т.д.). В консоли такое появляется:

"DELFORM ERROR:
TypeError: post.id.match(...) is null
    at getPNum (Dollchan_Extension_Tools.user.js:13744:12)
    at Thread (Dollchan_Extension_Tools.user.js:12249:10)
    at addFormContent (Dollchan_Extension_Tools.user.js:14132:14)
    at DelForm (Dollchan_Extension_Tools.user.js:14080:3)
    at initScript$ (Dollchan_Extension_Tools.user.js:2521:14)
    at tryCatch (Dollchan_Extension_Tools.user.js:1243:37)
    at invoke (Dollchan_Extension_Tools.user.js:1399:22)
    at continuer (Dollchan_Extension_Tools.user.js:3258:15)
    at async/< (Dollchan_Extension_Tools.user.js:3268:11)
" Dollchan_Extension_Tools.user.js:2529:0
Применение Mutation Events является устаревшим. Вместо них используйте MutationObserver. jquery.js:1:0
Метод getPreventDefault() является устаревшим. Для его замены используйте метод defaultPrevented. jquery.js:1:0

Firefox 38.0.1 + Greasemonkey 3.2 . Возможно это из-за того, что огнелис я еще не обновил, но пока нет возможности скачать новую версию.

**Comment by xDShot** [comment]
Спасибо :)
