### ISSUE TITLE
Автоподгрузка не работает на доброчане

### ISSUE THREAD

**Issue by suhr** [SthephanShinkufag/Dollchan-Extension-Tools#903]
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data at getJsonPosts/< (Dollchan_Extension_Tools.user.js:8228:11) at wrap/< (Dollchan_Extension_Tools.user.js:3689:19) at [85]
```

**Comment by SthephanShinkufag** [comment]
Есть ли этот баг с последней версией скрипта?

**Comment by suhr** [comment]
С последней версией нету.
