### ISSUE TITLE
"download thread" feature on 4chan.org (and probably similar chans)

### ISSUE THREAD

**Issue by devnei** [SthephanShinkufag/Dollchan-Extension-Tools#951]
Whenever I download a thread from 4chan and try to browse it, all the "**appearance settings**" (let's call it that, because I don't know what would the appropriate terminology be) **disappear**. It being the **saved webpage**. The page looks completely 1990's and it's all in standard colors. It doesn't happen with all imageboards, so I assume specific conditions must be set for 4chan's "appearance settings" to be retained after saving.
I tested it on Maxthon, Firefox and Pale Moon.
![screenshot_2](https://cloud.githubusercontent.com/assets/20477720/18037565/01f53868-6d5e-11e6-81ca-9f0c16469182.jpg)

**Comment by UserNaem** [comment]
Tried 2ch.hk and owlchan.ru, looks like the CSS doesn't work only on 4chan. Also, no favicon.

![program_manager 29 08 16 08-58-15](https://cloud.githubusercontent.com/assets/21028464/18039682/7c7f1ef4-6dbe-11e6-8387-a205ce00cd78.png)

**Comment by desudesutalk** [comment]
Addition: saved threads from [lainchan](https://lainchan.org/) (Tinyboard) doesn't work. After opening html file the thread `div` gets emptied. Console shows this error:

```
DELFORM ERROR:
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at TypeError (native)
    at Lainchan.getOp (...dollscript.js:17029:9)
    at new Thread (...dollscript.js:16013:42)
    at new DelForm (...dollscript.js:19441:12)
    at runMain$ (...dollscript.js:20697:38)
    at tryCatch (...dollscript.js:2368:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (...dollscript.js:2574:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (...dollscript.js:2393:21)
    at Function.continuer (...dollscript.js:3708:30)
    at HTMLDocument.<anonymous> (...dollscript.js:3723:11)
```

And result looks like this: https://lainchan.org/q/src/1471446426174.png

Debug:
```
{
    "version": "16.8.17.0",
    "location": "https://lainchan.org/q/res/10917.html",
    "nav": {
        "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36",
        "Firefox": false,
        "Presto": false,
        "WebKit": true,
        "Chrome": true,
        "Safari": false,
        "isGM": true,
        "isES6": false,
        "isChromeStorage": false,
        "isScriptStorage": false,
        "isGlobal": true,
        "scriptInstall": "Monkey",
        "hasTemplate": true,
        "hasWorker": true,
        "canPlayMP3": true,
        "canPlayWebm": true
    },
    "cfg": {
        "timePattern": "nn+dd+yy++w++hh+ii+ss",
        "addVocaroo": 0,
        "hideBySpell": false,
        "preLoadImgs": 1,
        "findImgFile": 1,
        "updThrDelay": "60",
        "hotKeys": 0,
        "inftyScroll": 0,
        "updScript": 0,
        "animation": 0,
        "txtBtnsLoc": 0,
        "addTextBtns": 3,
        "favIcoBlink": 1,
        "desktNotif": 1,
        "language": 1,
        "replyWinDrag": 1,
        "replyWinX": "left: 1162px",
        "replyWinY": "top: 167px",
        "textaWidth": 617,
        "textaHeight": 208,
        "cfgTab": "info"
    },
    "sSpells": [
        "#wipe(samelines,samewords,longwords,symbols,numbers,whitespace)"
    ],
    "perf": [
        ["Imageboard check", 0],
        ["Config loading", 0],
        ["Init", 3],
        ["Read my posts", 1],
        ["Replace delform", 0],
        ["Parse delform", 4],
        ["Parse postform", 6],
        ["Init page", 4],
        ["Add panel", 1],
        ["Init AJAX", 0],
        ["Preload images", 3],
        ["Audio links", 0],
        ["Video links", 0],
        ["Image names", 1],
        ["Reflinks map", 2],
        ["Apply CSS", 4],
        ["Display page", 0],
        ["Infinity scroll", 0],
        ["Hide posts", 2],
        ["Scroll page", 0],
        ["Total",31]
    ]
}
```
